= Object Detection Workshop with Red Hat OpenShift AI
:page-layout: home
:!sectids:

[.text-center.strong]
== Introduction

Welcome!

In this workshop, you'll learn an easy way to incorporate data science and AI/ML into an OpenShift development workflow.
As an example, you'll use an object detection model in several different ways.

You will:

* use Jupyter Notebooks to explore a pre-trained object detection model
* deploy the model using OpenShift AI model serving
* integrate the model into a real-time object detection app
* run offline scoring object detection pipelines
* refine and train the model

And all of this without having to install anything on your own computer, thanks to https://www.redhat.com/en/technologies/cloud-computing/openshift/openshift-data-science[Red Hat OpenShift AI].


=== Environment

https://developers.redhat.com/products/red-hat-openshift-data-science/download[Set up your Red Hat OpenShift AI environment]

If you haven't already got an instance of Red Hat OpenShift AI, find out more on the https://developers.redhat.com/products/red-hat-openshift-data-science/download[developer page].  There, you can spin up your own account on the *free OpenShift AI Sandbox* or learn about installing on *your own OpenShift cluster*.

=== Videos

https://developers.redhat.com/articles/2021/11/22/build-and-deploy-object-detection-model-using-openshift-data-science[Related Video Article - Build and deploy an object detection model using OpenShift AI, window="_blank"]

If you'd like to follow along with the accompanying videos of this workshop, you can find them in the article on the Red Hat Developer website or https://www.youtube.com/watch?v=C6xCFOwdFgY&list=PLf3vm0UK6HKoFFj46G26KeJLOr7FD9i86[watch on YouTube, window="_blank"] +
{nbsp} +

video::C6xCF OwdFgY[youtube,list=PLf3vm0UK6HKoFFj46G26KeJLOr7FD9i86, width=640, height=360]

== Start!

If you're ready,  xref:1-01-project-setup.adoc[let's start!]
